name: time_minder
description: "A new Flutter project."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.2.2
  video_player: ^2.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/rbg.png
    - assets/infog.png
    - assets/clip1.mp4
    - assets/clip2.mp4
    - assets/clip3.mp4
    - assets/clip4.mp4
    - assets/clip5.mp4
